### PR TITLE
update travis badge for migration to travis-ci.com

### PR DESCRIPTION
**Pull request by dgrove-oss**

### CODE REVIEW

**Review by rabbah — APPROVED** [review]

**Review by style95 — APPROVED** [review]
Thanks, Dave to handle this.

**Comment by style95** [comment]
It seems flake8 is failed to run.

```
Flake8: first round (fast fail) stops the build if there are any Python 3 syntax errors...
Traceback (most recent call last):
  File "/home/travis/.local/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/home/travis/.local/lib/python3.5/site-packages/flake8/main/cli.py", line 5, in <module>
    from flake8.main import application
  File "/home/travis/.local/lib/python3.5/site-packages/flake8/main/application.py", line 11, in <module>
    from flake8 import checker
  File "/home/travis/.local/lib/python3.5/site-packages/flake8/checker.py", line 18, in <module>
    from flake8 import processor
  File "/home/travis/.local/lib/python3.5/site-packages/flake8/processor.py", line 13, in <module>
    from flake8 import utils
  File "/home/travis/.local/lib/python3.5/site-packages/flake8/utils.py", line 16, in <module>
    from flake8._compat import lru_cache
  File "/home/travis/.local/lib/python3.5/site-packages/flake8/_compat.py", line 12, in <module>
    import importlib_metadata
  File "/home/travis/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 43, in <module>
    class PackageNotFoundError(ModuleNotFoundError):
NameError: name 'ModuleNotFoundError' is not defined
```

`importlib_metadata` has changed to submodule(`importlib.metadata`) since python3.8 and I suspect there are some issues in the flake8 though we are using python3.5 in Travis.

I think we can try to use python3.8 to clarify the issue.

**Comment by dgrove-oss** [comment]
trying newer python makes sense.  More generally, we are requesting xenial (16.04) as our ubuntu in travis.  We should probably move to 18.04 or 20.04.

**Comment by style95** [comment]
@jiangpengcheng Could you open a new PR to upgrade python and underlying ubuntu version by replicating this PR to update the Travis info as well?
We can see if that fixes the issue.

**Comment by jiangpengcheng** [comment]
ok

**Comment by style95** [comment]
@jiangpengcheng Would it be ok for me to work on this issue in parallel as this is the main bottleneck for now?

**Comment by jiangpengcheng** [comment]
@style95 sure

**Comment by dgrove-oss** [comment]
folded into #5042

**Pull request closed without merging**
