### PR TITLE
Remove deadcode from test helpers.

### LINKED ISSUE #3863: missing null check during TestUtils initialization
in this method https://github.com/apache/incubator-openwhisk/blob/37ce9b86048dafb0f369a5a5b05caa0136a26ef4/tests/src/test/scala/common/WhiskProperties.java#L297 there's a missing null check:

```
public static File getVCAPServicesFile() {
        String vcapServices = whiskProperties.getProperty("vcap.services.file");
        if (vcapServices.startsWith(File.separator)) {
            return new File(vcapServices);
        } else {
            return WhiskProperties.getFileRelativeToWhiskHome(vcapServices);
        }
    }
```

@jasonpet the `vcap` property does not appear to be used anymore in this repo:

https://github.com/apache/incubator-openwhisk/blob/9e5cec1f0e4b98c59e584d453b06a741be4a8c3b/tests/src/test/scala/common/TestUtils.java#L79

(per git blame https://github.com/apache/incubator-openwhisk/commit/f9b4f4841543ab27f4a7e974355802a811140483) is this used in the providers only now - if so i'm wondering if we can move it this code out.

### PR DESCRIPTION
**Pull request by rabbah**
Removes code that appears dead in this project/tests.
Closes #3863.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by mhenke1** [comment]
@rabbah we have found time to adapt the affected test cases. Thanks for waiting with the merge

**Comment by dubee** [comment]
@rabbah, @mhenke1, the providers use `getCredentials()`.

**Comment by jasonpet** [comment]
this needs to be reverted.  there are openwhisk repos that use the removed utils.  openwhisk is made up of many repos/projects and you cannot remove utils just because you do not see them being used in this repo/project.

**Comment by rabbah** [comment]
Thanks @dubee for pointing that out. I didn't mark this PR ready for review or notify the dev list because I did in fact intend to move the related code to the providers. I'm aware the providers need them (see the corresponding issue from July 2018). I'm not sure why this was merged yet (the message from Martin did suggest time was needed to address dependencies).

**Comment by rabbah** [comment]
FWIW, It's OK with me to revert the PR. I can reintroduce the patch when the downstream dependencies are resolved.

**Pull request merged**
