### PR TITLE
Update Travis build/test to use Xenial and Docker 18

### PR DESCRIPTION
**Pull request by jonpspri**
## Description

The legacy Travis build for OpenWhisk uses a depricated Travis engine and Docker 12.  While I know there are conversations around Docker 12 vs a later version, the use of the old Docker prevents use of certain good build features, namely Build Args for image selection and multi-stage builds.

This PR makes these changes:

- Bumps the Travis build to Xenial Ubuntu (the latest supported), which includes Docker 18.
- Patches Docker 18 service to listen on Port 4243 (TODO: let's get to shared sockets for everything)
- Adds parameterization for limits.invocations.per.minute to reduce spurious system test failures - separate PR pending
- Upgrades ephemeral CouchDB to `apache/couchdb:2.3` (to avoid a shared-storage bug) - see also PR #4202 
- Changes how Ansible detects ansible uptime to use the ansible-cli in the ansible Docker image, rather than make assumptions about the ansible network protocol - PR #4205
- Fix a redundant re-run of unit tests - separate PR pending

I will track other PRs and rebase if they're committed.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [X] Data stores (e.g., CouchDB)
- [X] Tests
- [X] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [X] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [X] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [X] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
@jonpspri this is great to see - sorry it sat for some time and now needs to rebase. It looks like though there's a few PRs conflated in here are they all necessary to upgrade to xenial?

**Comment by chetanmeh** [comment]
> Bumps the Travis build to Xenial Ubuntu (the latest supported), which includes Docker 18.
> Patches Docker 18 service to listen on Port 4243 (TODO: let's get to shared sockets for everything)

The Travis build has now been moved to Xenial with #4683

**Comment by dgrove-oss** [comment]
Should we close this as out-of-date?

**Comment by rabbah** [comment]
👍

**Pull request closed without merging**
