### PR TITLE
fixes to use different secrets, show the results in the log

### PR DESCRIPTION
**Pull request by msciabarra**
Changes to run without errors.

## Description

My github actions pass the AWS_ACCESS_ID secrets to the build but since they are pull requests they are empty. 

This enables some tests usually skipped that fails. So I changed the name of the variables used to upload logs.
Furthermore I made optional the upload of logs and slack notification and printed the results of the test in the job run for inspection.

Now all tests pass.

Build fails because of overlap of env variables

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Scheduler
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md#coding-standards) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by sciabarracom** [comment]
My github actions pass the AWS_ACCESS_ID secrets to the build but since they are pull requests they are empty. This enables some tests and make some of them fail. So I changed the name of the variables used to upload logs. Furthermore I made optional the upload of logs and slack notification and printed the results of the tes in the job run for inspection. Now all test pass.

**Review by style95 — APPROVED** [review]

**Comment by style95** [comment]
BTW, if we change the variable, how can we test the S3 uploading tests?

**Comment by sciabarracom** [comment]
> BTW, if we change the variable, how can we test the S3 uploading tests?

we cannot test it anyway and they are not tested with travis - secrets are not passed to pull requests (otherwise it would be trivial to grab them, just make a pull request that dumps and writes them somewhere)

you can test them only locally and if you have all the expected environment variables, what I did wrong was to use the environment variables that activated the tests

**Comment by msciabarra** [comment]
Screenshot 2022-12-22 at 05 17 07

This is odd... when I remove the AWS variables this test starts to fail...
If I enable them it will be the S3StorageTest to fail
I need to figure out why.

**Pull request merged**
