### PR TITLE
Api Gateway support in OpenWhisk Standalone mode

### PR DESCRIPTION
**Pull request by chetanmeh**
Enable using api gateway with standalone mode (#4516). 

## Description

Enables launching api gateway with `--api-gw` option

```
java -jar openwhisk-standalone.jar --api-gw 
```

With `-a` flag following tasks would be performed

1. Install route management actions for `createApi`, `deleteApi` and `getApi`
2. Launch the redis server and wait for it to be ready
3. Compute the host ip (see Host url logic section below)
4. Launch the Api gateway container (at 3234 port by default) and pass the redis ip and local host ip

### Host url logic

Due to issue in #4523 and apache/incubator-openwhisk-apigateway#345 we need to compute the actual ip for `host.docker.internal` and pass it as part of `BACKEND_HOST` env variable

### Port Handling

This PR requires only 2 ports to be actually free 3233 for main server and 3234 for api gateway management port.

For redis and api gateway api port it tries to use std port (6479 for redis and 9000 for api). If they are not free it would try to allocate a random port and use them. This should minimize port conflict for end users

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
`Enables launching api gateway with -a option`

-a is a little cryptic i think but dont have a better 1 letter suggestion... is there a long form `--apigw` or `--gw` option (of course those are longer)

**Comment by chetanmeh** [comment]
There is long form `--api-gw `

**Comment by chetanmeh** [comment]
To try out this feature follow steps below

```
# Fetch custom docker build of apigateway which has apache/incubator-openwhisk-apigateway#347 fixed
$ docker pull chetanmeh/apigateway

# Download the openwhisk-standalone jar
$ wget https://github.com/chetanmeh/incubator-openwhisk/releases/download/v0.11/openwhisk-standalone.jar
$ java -Dwhisk.standalone.api-gateway.image=chetanmeh/apigateway -jar openwhisk-standalone.jar --api-gw
```

**Comment by chetanmeh** [comment]
Build now passed along with testcase for the gateway support in Standalone. @rabbah can you review once more

**Pull request merged**
