### PR TITLE
add standalone to dockerhub

### PR DESCRIPTION
**Pull request by sciabarra**
## Description

Add the standalone docker image to docker hub

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [x] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by mcdan** [comment]
How do we feel about the image name:  https://github.com/apache/openwhisk/blob/master/core/standalone/build.gradle#L28 `standalone`?
Should we update the docs to use this as the "quickstart" seeing as it's a lot quicker?

**Comment by chetanmeh** [comment]
> Should we update the docs to use this as the "quickstart" seeing as it's a lot quicker?

I thought using that later but then thought it gives a feeling that this can be used as a quickstart for actual usage. So used convention used by [Spark Standalone](https://spark.apache.org/docs/latest/spark-standalone.html). But if people think we can change it

**Comment by dgrove-oss** [comment]
No strong opinion in the image name.  Since the jar file, configuration, etc. are also called standalone it seems plausible to me.

**Comment by sciabarra** [comment]
I prefer standalone for consistency with the others

**Comment by dgrove-oss** [comment]
confirming that it worked as expected.  openwhisk/standalone:nightly is available on dockerhub

**Pull request merged**
