### PR TITLE
Revert cycle handling.

### PR DESCRIPTION
**Pull request by style95**
## Description
This is to revert the recent change.
https://github.com/apache/openwhisk/pull/5251 is introduced to handle the cyclic activations storm in a queue manager.
But with this change, I observed severe performance degradation.

This is the performance measurement with the current master.
image

And this is the result of this change.
image

This is because even for normal activations, the queue manager tries to recover a queue.
There is a gap between the time that leader election is done(etcd data is written) and the queue is ready.
If activations come during that time, the queue manager tries to recover a queue and it increases the wait time.

And the result is well aligned with the one I performed for the initial run.
https://github.com/apache/openwhisk/pull/5194#issuecomment-1019875232

Since the cycle in a critical path is also a big problem, we must handle it.
But until we find a better way to address it I think it would be better to revert this change.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [x] Scheduler
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md#coding-standards) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by style95** [comment]
I opened an issue for the cycle.
https://github.com/apache/openwhisk/issues/5301

**Review by ningyougang — APPROVED** [review]

**Review by jiangpengcheng — APPROVED** [review]

**Comment by bdoyle0182** [comment]
Do you think this one is related to any of the bugs I've reported to you?

**Review by bdoyle0182 — APPROVED** [review]

**Comment by bdoyle0182** [comment]
Also when was this introduced? Has this been on the open source branch since we said the scheduler was functional or was it added in a recent commit?

**Comment by style95** [comment]
@bdoyle0182 
If you haven't seen any huge logs printing the same repeatedly, you haven't hit the issue.
The change I revert here is relatively recently added after I made a change to run the scheduler.
This is the change: https://github.com/apache/openwhisk/pull/5251

**Pull request merged**
