### PR TITLE
Remove git property plugin.

### PR DESCRIPTION
**Pull request by style95**
This is to release OpenWhisk 1.0.0.

### CODE REVIEW

**Comment by rabbah** [comment]
Looks ok to me. Could we have hardcoded the values also?

**Review by rabbah — APPROVED** [review]

**Comment by style95** [comment]
@rabbah You meant, adding one commit to the 1.0.0 branch to hardcode the commit version which would be displayed?

**Comment by dgrove-oss** [comment]
I was playing around with something last night too, but didn't quite validate it was working.  It's possible to make the git.properties task optional by adding this to standalone's build.gradle, but not changing the code.
```
gitProperties {
    failOnNoGitDirectory = false
}

```
You then get a splash screen like:
```
+ java -Dwhisk.standalone.host.name=openwhisk -Dwhisk.standalone.host.internal=172.17.0.3 -Dwhisk.standalone.host.external=localhost -jar openwhisk-standalone.jar --no-browser

        ____      ___                   _    _ _     _     _
       /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
  /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
 /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
 \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\
  \___\/ tm           |_|
    
================================================================================
Running pre flight checks ...

Local Host Name: openwhisk
Local Internal Name: 172.17.0.3

[  OK   ] 'docker' cli found. (Docker version 18.06.3-ce, build d7080c1)
[  OK   ] 'docker' version 18.6.3 is newer than minimum supported 18.3.0
[FAILURE] 'docker' not found to be running. Failed to run 'docker info'
[  OK   ] 'wsk' cli found. (2019-09-23T17:46:38.323+0000)
[  OK   ] 'wsk' configured for namespace [guest].
[  OK   ] 'wsk' configured to connect to http://openwhisk:3233.
[  OK   ] Server port [3233] is free

================================================================================

```

**Comment by dgrove-oss** [comment]
I haven't submitted the "make it optional" PR because I have a more fundamental problem.  At least for me, the standalone docker image doesn't work at all (see #5016).

**Comment by style95** [comment]
@dgrove-oss 
I confirmed after adding this I could build and run the 1.0.0 artifact.

```
gitProperties {
    failOnNoGitDirectory = false
}
```

Could you open a PR for this?
I really want to release the 1.0.0 version and keep going on the scheduler work.

We could also make it work with higher versions of Docker, but I think that is out of scope for 1.0.0.
And our guide is using `18.06.3` for now.
https://github.com/apache/openwhisk/blob/master/tools/ubuntu-setup/docker.sh#L38

**Comment by dgrove-oss** [comment]
I will submit a PR with the gitProperties change.  

At some level, I agree that updating the docker version is not release blocking.  However, I would like to try to see if it can be fixed just by upgrading the docker version we put in the standalone docker image.  It is unfortunate that our default instructions to run standalone (run start.sh to launch the standalone:1.0.0 image) don't work out of the box on MacOS with latest Docker Desktop.

None of that needs to stall the scheduler work however.  We have the 1.0.0 branch.  New work can continue on the master branch without waiting for 1.0.0 to be cut.  We can cherry-pick commits to 1.0.0 as needed.

**Comment by dgrove-oss** [comment]
As discussed, closing in favor of #5018

**Pull request closed without merging**
