### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
~Blocked by #5459~
~* #5459 (merged)~

Create an automatic pull request to upgrade [all `.github/workflows/XXX.yml` files](https://github.com/apache/openwhisk/tree/master/.github/workflows):
```diff
-       uses: actions/checkout@v3
+       uses: actions/checkout@v4
```

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Scheduler
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md#coding-standards) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by style95** [comment]
I didn't dig into it but around 20 unit tests fail in this PR.

**Comment by cclauss** [comment]
You get the same results fixing a typo…
* #5461

**Comment by cclauss** [comment]
Unit test changes copied from
* #5459

**Comment by cclauss** [comment]
Rebased.

**Review by style95 — APPROVED** [review]

**Pull request merged**
