### PR TITLE
Skip travis jobs if pr only touches docs.

### PR DESCRIPTION
**Pull request by rabbah**
Exclude travis jobs if a PR only touches documentation. Only scan code will run.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [x] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
@dgrove-oss wdyt about merging this PR.
I will test it out on #4880. The intent is to skip tests for md related changes and only run scancode.

I left perf tests enabled in this PR intentionally to see if it works as designed.

**Comment by dgrove-oss** [comment]
If we want to optimize for quick merge of documentation-only PRs, we should probably short-circuit the step of the build that compiles & deploys openwhisk too.

**Comment by rabbah** [comment]
Can we merge this to see if this approach will actually work? It will already be an improvement. Some of the earlier steps will need to be moved into bash scripts - there's no way that i found to exclude travis steps/jobs because it doesn't evaluate true conditions.

**Comment by dgrove-oss** [comment]
don't object to merging; just observing that as-is it creates 7 jobs, each of which will run for about 8 minutes (mainly due to the setup script).

**Comment by rabbah** [comment]
Not working as intended - the build should have been normal but all the tests are being skipped.

**Pull request closed without merging**
