### PR TITLE
Add reason parameter for wskadmin tool

### PR DESCRIPTION
**Pull request by steffenrost**
For auditability reasons it would be beneficial to also specify a reason for the set limits command (why was a certain namespace throttled on a given limit).

This PR adds a reason parameter to the `wskadmin` tool. It is the most simple implementation where the reason value would be overwritten by each new set limits command. 

```
{
  "_id": "<namespace>/limits",
  "firesPerMinute": 100,
  "invocationsPerMinute": 200,
  "reason": "throttle namespace on invocations per minute because of .."
}
```

In order to have a kind of audit trail/log available the history of changes on the `/limits` documents needs to be stored. Please find below a sample of the `/limits` document containing an audit log. However this PR does not implement an audit log but only adds a single reason parameter to the `/limits` document as described above.

```
{
  "_id": "<namespace>/limits",
  "firesPerMinute": 100,
  "invocationsPerMinute": 200,
  "reasons": [
    {
      "reason": "throttle namespace on fires per minute because of ..",
      "time": "1562317956422",
      "limits": {
        "firesPerMinute": 100
      }
    },
    {
      "reason": "throttle namespace on invocations per minute because of ..",
      "time": "1562318956422",
      "limits": {
        "invocationsPerMinute": 200
      }
    }
  ]
}
```

## Description
This code change add an additional reason parameter to the wskadmin tool to store in addition the reason for the set limits command for auditability reasons..

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [x] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by rabbah** [comment]
Please bring this to the dev list. Also this should likely be done on the wskadmin next tool as the plan had been to deprecate and remove this tool.

**Comment by rabbah** [comment]
Thanks Stefan. Have a way to audit changes makes sense to me. See my previous comment though.

**Comment by steffenrost** [comment]
@rabbah Thanks for your comments. Do you know the timeline for deprecate and remove the wskadmin tool?

**Comment by rabbah** [comment]
it has sort of slipped through the cracks - which leads to a situation like this one where functionality is added to `wskadmin` but not wskadmin-next.

@chetanmeh can comment - but this is a good topic for the dev list.

**Comment by chetanmeh** [comment]
So far as there has not been much use of any store apart from CouchDB there was not much pressing need for doing away with wskadmin. Probably we can revisit that aspect and decide whether it makes sense to have 2 admin toolings or deprecate wskadmin and add all new features in wskadmin-next

**Comment by steffenrost** [comment]
@rabbah thanks for your comments on the dev list. So do we want to go forward with the change proposed in this PR? 
Besides the change in wskadmin and the test you mentioned, what else needs to be done? Do I have to cover the wskadmin next tool in this PR as well or would this be a separate effort/PR?

**Comment by rabbah** [comment]
I suggest: 

1. open an Issue to cover adding this feature to -next
2. add a test in this PR

**Comment by steffenrost** [comment]
> I suggest:
> 
> 1. open an Issue to cover adding this feature to -next
> 2. add a test in this PR

Thanks for your answer. I won't have the time to continue to work on the PR this week and the following two weeks, so will most probably continue by end of August. I hope this is not a problem.

**Comment by steffenrost** [comment]
> I suggest:
> 
> 1. open an Issue to cover adding this feature to -next
> 2. add a test in this PR

@rabbah I modified the `WskAdminTests` to also set/query the reason when running the `adjust throttles for namespace` testcase, could you please have a look/review?

**Comment by rabbah** [comment]
This was approve 9/19 but never merged. Closing as abandoned.

**Pull request closed without merging**
