### PR TITLE
making optional logs upload and slack notification, and showing test results in the job run

### PR DESCRIPTION
**Pull request by msciabarra**
making optional logs upload and slack notification

## Description

errors in build for missing env vars 

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Scheduler
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [ ] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [ ] I reviewed the [style guides](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md#coding-standards) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by style95** [comment]
Seems S3-related tests are failing.
image

**Comment by msciabarra** [comment]
Yes true. AWS S3 tests are NOW failing, and I guess this is happening simply because someone removed the AWS_BUCKET secret that was there before. I used the bucket to upload logs there and I am sure he was not happy.

**Comment by msciabarra** [comment]
Hi I made a few changes, mostly I made the s3 test skipped it the bucket is not available, fixed a compilation error and now the build works. Can you merge?

**Comment by msciabarra** [comment]
forget about this - I misunderstood a few things - restarting the patch

**Pull request closed without merging**
