### PR TITLE
Add CPU limit mode to container scheduling, contrast with CPU share mode

### PR DESCRIPTION
**Pull request by BillZong**
### Goals

Currently, the container scheduling strategy is CPU share, using `docker run --cpu-shares`. 
And we use `poolConfig.userMemory` to specify **every** `Invoker` node's memory pool size. *(Did I miss sth? Do me a favor to correct me if needed.)*
It's easy to understand, and robust enough to fit most of the deployment case.

But what if we wanna deploy `Invoker` in some resource-limited machine (eg. 4 cores CPU and 8 GB memory, only use 4 cores and 4GB memory), or K8S nodes with different memory resource?
And How to figure out the best `userMemory` in a cluster without boiling CPUs and saving testing time, if most of the actions are CPU consuming, such as AI functions?

### Details

Add **CPU limit mode** to make things happened.

* Add a configuration `whisk.cpu.control-enabled` to `application.conf`.
    * `false` by **default**, which means we use the good old way.
    * `true` to turn on the scheduling feature.
* When turned on
   * Each invoker would report its CPU threads info (number of CPU logic cores) when registering.
   * `ShardingContainerPoolBalancer` use CPU slots the same behavior as memory slots.
   * `ContainerPool` use CPU (first) and memory (second) for pool space calculation.
   * `ContainerFactory` add a new method `createCPUContainer()`.
   * `DockerContainer` add `createByCPU()` with `docker run --cpus` implementation.
   * `Action` add CPU limit annotations, `min/std/max`.
* Add CLI supporting
    * Add `--cpu` parameter to `wsk` CLI.
    * The commit done and tested.
    * The PR not uploaded yet.
* Add K8S deploy options
    * Add `whisk.limits.actions.cpu` configuration.
    * The commit done and tested.
    * The PR not uploaded yet.

### Tests

* Done locally and in a 4-cloud-nodes K8S cluster.
    * Invoker node with 4 CPUs and 4 GB memory as most.
    * AI function. `--docker` creation, `blackbox` run type, which take 300 MB.
    * **Almost identical** as the best deployment setting case.

### TODO:

* [ ] More documentation on this topic.
* [ ] Coverage tests.
* [ ] More measurement tests.
* [ ] Sequence action behavior tests.
    * Not familiar with these concepts and execution process.

***Issue needed? Slack talk needed?***

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#4650)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [x] Loadbalancer
- [x] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [x] Tests
- [x] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [x] I added tests to cover my changes.
- [x] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by style95** [comment]
Hi @BillZong any updates on this?

**Comment by BillZong** [comment]
Not yet. Felt sorry about that. :(
Had been heavily stuck in another project recently, and not any update right now.

Failed in CI performance tests last time.
Any improvements or suggestions would be appreciated.

**Comment by style95** [comment]
@BillZong nothing to be sorry.
Thank you for this change.

I will give it a shot.

**Comment by markusthoemmes** [comment]
This seems to be a huge chunk of code changes and non-trivial on top of that. Does this maybe warrant a discussion on the dev-list? I feel like this at least needs to be broken into smaller chunks to be able to review it properly.

**Comment by BillZong** [comment]
@markusthoemmes Thanks for your kindly opinion.
The dev-list had already sent but got no reply recently.
Smaller chunks would be a better choice for making this PR more readable, although separating it would make the overall goal less clear.

I'll devote to it during/after my long holidays.

**Comment by style95** [comment]
@BillZong 
Thank you for your contribution again and sorry for the late response. 
I marked this PR as stale to close soon due to long inactivity.
Please let me know if you would work on it again.

**Pull request closed without merging**
