### PR TITLE
CouchDB support in OpenWhisk Standalone mode

### PR DESCRIPTION
**Pull request by chetanmeh**
Enable using CouchDB with standalone mode (#4516). This would be useful for cases where users would like to save there changes upon restarts.

## Description
Enables launching CouchDB with `--couchdb` option

```
java -jar openwhisk-standalone.jar --couchdb
```

With this flag following tasks would be performed

1. CouchDB server would be started. By default at port 5984. If thats busy then at some random port
2. CouchDB would be configured with required databases and views
3. DB files would stored under `~/.openwhisk/standalone` folder
4. Launching with `--clean` option would lead to recreating the db

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [x] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [x] I added tests to cover my changes.
- [x] My changes require further changes to the documentation.
- [x] I updated the documentation where necessary.

### CODE REVIEW

**Comment by chetanmeh** [comment]
This PR is now ready for review

**Comment by rabbah** [comment]
Sorry fat finger! I was trying this out and tabbed to the wrong place.

**Comment by rabbah** [comment]
@chetanmeh the docs for standalone should get promoted to be "front and center" of our docs for getting started on this repo.

**Comment by chetanmeh** [comment]
> the docs for standalone should get promoted to be "front and center" of our docs for getting started on this repo.

@rabbah Thats the plan. Just waiting for core repo release (see also #4525 ) such that I have a url for users to download the pre built runnable jar. Once that is done we can the update the docs in repo and website to refer people to this approach as the first step

**Pull request merged**
