### PR TITLE
Send a queue removed message to the queue manager

### PR DESCRIPTION
**Pull request by style95**
This is to handle the issue reported in https://github.com/apache/openwhisk/pull/5388 in another way.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Scheduler
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md#coding-standards) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Comment by bdoyle0182** [comment]
This LGTM we need this as well but I think it's important to have the additional safeguard from the state timeout never occurring in the removing state creating an activation cycle such that the queue is never shut down so will still go ahead with merging that as well if you approve it.

**Comment by style95** [comment]
@bdoyle0182 
My bad, I added another missing part.

So both `cleanUpDataAndGotoRemoved()` and `cleanUpActorsAndGotoRemoved()` should send a queue removed message to the queue manager.

**Comment by bdoyle0182** [comment]
Since this will be called from every shutdown case, I just want to make sure that there aren't any new race conditions created. Would it be possible for the queue removed message to be sent twice if it's called from here now and it was sent from another shutdown case such that the queue is removed from the manager map and then a new queue is created and this fsm sends another queue removed message removing it from the parent map after the new queue is created? I'm not sure if that could happen or matters, but want to check

**Comment by bdoyle0182** [comment]
Will approve this so long as we're confident sending queue removed to the parent from these locations cannot create a new race condition.

**Comment by style95** [comment]
Once the queue manager receives a queue removed message, it will just remove the corresponding reference from queue pool and send an ack back to the sender.
If there is any logic to re-add the reference to the queue pool then there might be a race condition, but it always removes the reference and no race condition happens.
https://github.com/apache/openwhisk/blob/master/core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala#L204

One concern could be multiple acks sent from the queue manager, but it will also be handled by the wildcard case if there is no match for a certain state.
https://github.com/apache/openwhisk/blob/master/core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala#L670

**Comment by bdoyle0182** [comment]
LGTM

**Pull request merged**
