### PR TITLE
finish/failed uncompleted transaction

### PR DESCRIPTION
**Pull request by jiangpengcheng**
Just find that in some cases, `ElasticSearchActivationStore` doesn't complete transaction.

## Related issue and scope

- [ ] I opened an issue to propose and discuss this change (#????)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Scheduler
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

**Review by ningyougang — APPROVED** [review]

**Comment by ningyougang** [comment]
LGTM

**Review by rabbah — COMMENTED** [review]
LGTM.

**Review by rabbah — APPROVED** [review]

**Comment by dgrove-oss** [comment]
Should this be merged?

**Comment by jiangpengcheng** [comment]
oh, I will rebase master branch first to ensure there is no error

**Pull request merged**
