### PR TITLE
Remove path projections on web actions.

### PR DESCRIPTION
**Pull request by rabbah**
This removes the extensions on web actions. This is a breaking change. 

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#4352)

## My changes affect the following components

- [x] API
- [x] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [x] Documentation

## Types of changes

- [ ] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [x] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [x] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [x] I updated the documentation where necessary.

### CODE REVIEW

**Comment by mhenke1** [comment]
@rodric please wait with merging this PR. It looks like we have customers using the feature extensively. I am still investigating. If so, it might be necessary to put the change behind a feature flag to allow coordinated deprecation.

**Comment by mhenke1** [comment]
IBM Functions sees uses of `.text`and `.json`projections. 
I have started a [discussion on the mailing list](https://lists.apache.org/thread.html/aa9e80a3da06f0355a61fd890bbd666c21a8ccf37d8be93d1bbd2b00@%3Cdev.openwhisk.apache.org%3E) to allow a controlled deprecation phase.
PLEASE DO NOT MERGE NOW

**Comment by mhenke1** [comment]
PLEASE DO NOT MERGE before December 1st 2019
Please see  [discussion on the mailing list](https://lists.apache.org/thread.html/aa9e80a3da06f0355a61fd890bbd666c21a8ccf37d8be93d1bbd2b00@%3Cdev.openwhisk.apache.org%3E) for details

**Comment by rabbah** [comment]
This is now ready to merge.

**Comment by rabbah** [comment]
@mhenke1 want to press the green button or shall I?

**Comment by mhenke1** [comment]
@rabbah I have pressed it. Thanks for your patience.

**Pull request merged**
