### PR TITLE
Using the gradle eclipse plugin to generate eclipse project files

### PR DESCRIPTION
**Pull request by markusthoemmes**
This provides proper integration with Eclipse using gradle to generate project and classpath files.

### CODE REVIEW

**Comment by psuter** [comment]
How do I use this? Is one top-level `gradle eclipse` enough?

**Comment by markusthoemmes** [comment]
Should be yes, `gradle eclipse` and then import as existing project in Eclipse.

**Comment by psuter** [comment]
It seems to create fewer projects than we used to have. E.g. no project for `common`?

**Comment by jeremiaswerner** [comment]
cool stuff. thanks ;)

**Pull request merged**
